name: afro前端

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 安装node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: 安装依赖
        run: npm ci
      - name: 打包
        run: npm run build

      - name: 发布到腾讯云
        uses: easingthemes/ssh-deploy@main
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # SCP参数
          ARGS: '-avzr --delete'
          # 源目录
          SOURCE: '/dist/'
          # 服务器ip
          REMOTE_HOST: ${{ secrets.REMOTE_TXHOST }}
          # 用户
          REMOTE_USER: 'root'
          # 目标地址
          TARGET: '/project/html'
      - name: Execute command on Tencent Cloud server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.REMOTE_TXHOST }}
          username: 'root'
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            docker restart afro-nginx
